Merged official debian tree.

diff --git a/debian/autoradio.postinst b/debian/autoradio.postinst
--- a/debian/autoradio.postinst
+++ b/debian/autoradio.postinst
@@ -27,7 +27,7 @@ GROUPMOD="/usr/sbin/groupmod"
 ID="/usr/bin/id"
 
 set -e
-set -x
+#set -x
 
 case "$1" in
     configure)
@@ -60,16 +60,25 @@ if [ "$IUID" = "NONE" ] ; then # we must do sth :)
 
 # 3. Add the system account.
 #    Issue a debconf warning if it fails. 
-  if $GROUPMOD $AUTORADIO > /dev/null 2>&1; then 
-    # autoradio group already exists, use --ingroup
-    if ! $ADDUSER --home /usr/share/autoradio/ --gecos autoradio --disabled-password --disabled-login --no-create-home --ingroup $AUTORADIO $AUTORADIO; then
-      echo "The adduser command failed."
-    fi
-  else
-    if ! $ADDUSER --home /usr/share/autoradio/ --gecos autoradio --disabled-password --disabled-login --no-create-home --group $AUTORADIO $AUTORADIO; then
-      echo "The adduser command failed."
-    fi
-  fi
+#  if $GROUPMOD $AUTORADIO > /dev/null 2>&1; then 
+#    # autoradio group already exists, use --ingroup
+#    if ! $ADDUSER --home /usr/share/autoradio/ --gecos autoradio --disabled-password --disabled-login --no-create-home --ingroup $AUTORADIO $AUTORADIO; then
+#      echo "The adduser command failed."
+#    fi
+#  else
+#    if ! $ADDUSER --home /usr/share/autoradio/ --gecos autoradio --disabled-password --disabled-login --no-create-home --group $AUTORADIO $AUTORADIO; then
+#      echo "The adduser command failed."
+#    fi
+#  fi
+#fi
+        if ! getent group autoradio > /dev/null 2>&1 ; then
+            addgroup --system autoradio --quiet
+        fi
+        if ! id autoragio > /dev/null 2>&1 ; then
+            adduser --home /usr/share/autoradio/ --gecos autoradio \
+                --ingroup autoradio --disabled-password --disabled-login \
+                --no-create-home autoradio
+        fi
 fi
 set -e
 
